GET http://127.0.0.1:3000/ejemplo HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "a@gmail.com",
  "password": "123456"
}

###
POST http://127.0.0.1:3000/registro HTTP/1.1
Content-Type: application/json

{
  "email": "a@gmail.com",
  "name": "lucas",
  "password": "123456"
}
###
POST http://127.0.0.1:3000/exam/quiz HTTP/1.1
Content-Type: application/json

//PARA PRUEBAS DE JWT

### 
POST http://127.0.0.1:3000/23232/exam HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJsdWNhcyIsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJpYXQiOjE3ODk0ODQyNTAsImV4cCI6MTc4OTQ4NTE1MH0.ZkKDa5HvVVJU1uwL5YUDUTdEUBX1voCLGO8zWxmzyMk
x-refresh-token: 1f06ff44c048aa395d863c54ce28e64ebf0f84ae739555cfe45004d7cd4d597f

{
  
}

//PRUEBA DE RENOVACION CON EL REFRESH TOKEN
### 
POST http://127.0.0.1:3000/renueve_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJsdWNhcyIsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJpYXQiOjE3ODk0ODQzMTQsImV4cCI6MTc4OTQ4NTIxNH0.v5AfGRE7Ap2-IOIgaWF0boO9l3rx0xmL1kxohNqt80U"
x-refresh-token: 875c65d79d92b4bea0af79a3a75b3d2b6fbb81a3065b65d2536f168a211da3a8
Content-Type: application/json

{
  "nombre": "lucas",
  "email": "a@gmail.com"
}
###
GET http://127.0.0.1:3000/strike?id=4&date=2026-09-29T06:00:00.000Z HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Imx1Y2FzIiwidXNlckVtYWlsIjoiYUBnbWFpbC5jb20iLCJpYXQiOjE3ODk0ODQ0NjMsImV4cCI6MTc4OTQ4NTM2M30.R0IW6IrP3tUBW2kOa26uaTfA3dq-FuVC4SK3Xn3ZmJo

###
GET http://127.0.0.1:3000/logout?id=3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJsdWNhcyIsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJpYXQiOjE3ODkzOTg0MzQsImV4cCI6MTc4OTM5OTMzNH0.spn3M1mYuRdgcIO4sSWe-h8mLA2vv8CONxxk5VOpPgs
x-refresh-token: 1fa2af4f861cbb0c9907dc24ff1d573fe2b0826bd77ec185b0ded4edf8490eb3